### ISSUE TITLE
New docker extension self-publish process

### ISSUE THREAD

**Issue by benja-M-1** [boringproxy/boringproxy-docker-extension#2]
Hi @anderspitman 👋 

I am Ben from the Docker Extensions team 😃 In case you didn't know, we released a new way to publish your extension on the marketplace last week: https://docs.docker.com/desktop/extensions-sdk/extensions/publish/. 

Would you be interested in submitting your extension?

**Comment by anderspitman** [comment]
Hey Ben. I did actually see the self-publishing feature, which is great. I'm actually working on a different extension that will hopefully be released soon, but this one was mostly to get familiar with the SDK.

**Comment by benja-M-1** [comment]
Alright! Glad to know you are working on another one 🤩 looking forward to trying it!
